CREATE DATABASE "sotsuken-network";
CREATE DATABASE "sotsuken-network-test";

-- アプリ用ユーザとしてuserを作成する。
-- NOBYPASSRLSはデフォルトだが明示しておく。
CREATE USER asami WITH NOBYPASSRLS;


-- テーブル作成ごとにGRANTしなくて済むようDEFAULT PRIVILEGESを設定する。
\c sotsuken-network
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO asami;
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT USAGE ON SCHEMAS TO asami;

\c sotsuken-network-test
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO asami;
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT USAGE ON SCHEMAS TO asami;