CREATE DATABASE "sotsuken-users";
CREATE DATABASE "sotsuken-users-test";


-- NOBYPASSRLSはデフォルトだが明示しておく。
CREATE USER asami WITH NOBYPASSRLS;


-- テーブル作成ごとにGRANTしなくて済むようDEFAULT PRIVILEGESを設定する。
\c sotsuken-users
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO asami;
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT USAGE ON SCHEMAS TO asami;

\c sotsuken-users-test
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO asami;
ALTER DEFAULT PRIVILEGES FOR USER postgres GRANT USAGE ON SCHEMAS TO asami;